### Label Encoding

In [2]:
import pandas as pd

df = pd.DataFrame({"name": ["wscube", "cow", "cat", "dog", "black"]})
df

     name
0  wscube
1     cow
2     cat
3     dog
4   black

In [3]:
from sklearn.preprocessing import LabelEncoder

In [4]:
le = LabelEncoder()
df["en_name"] = le.fit_transform(df["name"])

In [5]:
df

     name  en_name
0  wscube        4
1     cow        2
2     cat        1
3     dog        3
4   black        0

In [6]:
dataset = pd.read_csv("../../datasets/loan_dataset.csv", encoding='latin1')

dataset.head(5)

,Loan_ID,Gender,Married,Dependend,Education,Self_Employment,Application,Coapplication,LoanAmount,Credit_History,Property_Area,Loan_status
0,LP1001,NaN,No,3+,Graduate,Yes,5745.07,1889.39,155.91,NaN,Rural,N
1,LP1002,Male,Yes,3+,Not Grad,Yes,7284.54,1812.68,120.63,NaN,Semiurban,Y
2,LP1003,Female,Yes,1,Not Grad,No,7368.82,2613.95,111.22,0.0,Urban,Y
3,LP1004,NaN,Yes,1,Not Grad,NaN,5813.84,1629.27,111.37,0.0,Urban,Y
4,LP1005,Female,Yes,NaN,Not Grad,NaN,5362.94,469.38,61.00,0.0,Rural,N

In [7]:
dataset["Property_Area"].unique()

<StringArray>
['Rural', 'Semiurban', 'Urban']
Length: 3, dtype: str

In [8]:
la = LabelEncoder()
la.fit(dataset["Property_Area"])

LabelEncoder()

In [9]:
la.transform(dataset["Property_Area"])

array([0, 1, 2, ..., 1, 1, 2], shape=(1050,))

In [10]:
dataset["Property_Area"] = la.transform(dataset["Property_Area"])

In [11]:
dataset.head(5)

,Loan_ID,Gender,Married,Dependend,Education,Self_Employment,Application,Coapplication,LoanAmount,Credit_History,Property_Area,Loan_status
0,LP1001,NaN,No,3+,Graduate,Yes,5745.07,1889.39,155.91,NaN,0,N
1,LP1002,Male,Yes,3+,Not Grad,Yes,7284.54,1812.68,120.63,NaN,1,Y
2,LP1003,Female,Yes,1,Not Grad,No,7368.82,2613.95,111.22,0.0,2,Y
3,LP1004,NaN,Yes,1,Not Grad,NaN,5813.84,1629.27,111.37,0.0,2,Y
4,LP1005,Female,Yes,NaN,Not Grad,NaN,5362.94,469.38,61.00,0.0,0,N