In [1]:
import pandas as pd

# read csv file
df = pd.read_csv('../../datasets/players_20.csv', encoding='latin1')

# set index
df.set_index('short_name', inplace=True)

# select column
df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']]

In [2]:
# show dataframe
df.head(5)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

### sample()

In [3]:
# extract 10 random elements from the "nationality" column
df['nationality'].sample(10, random_state=99)

short_name
R. Alvarado               Mexico
Qiao Wei                China PR
E. Paredes                 Chile
K. Stoyanov             Bulgaria
M. ChudÃ½               Slovakia
D. Sundaram                India
R. Gagliardini             Italy
G. Debeljuh              Croatia
Kim Seung Yong    Korea Republic
M. Hansen                Denmark
Name: nationality, dtype: object

In [4]:
# extract a random 20% sample of the dataframe
df.sample(frac=0.2, random_state=99)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
R. Alvarado,Roberto Alvarado,20,1998-09-07,176,70,Mexico,Cruz Azul
Qiao Wei,Wei Qiao,31,1987-07-20,187,75,China PR,Shenzhen FC
E. Paredes,Esteban Paredes,38,1980-08-01,178,82,Chile,Colo-Colo
K. Stoyanov,Krum Stoyanov,27,1991-08-01,177,71,Bulgaria,Bulgaria
M. ChudÃ½,Martin ChudÃ½,30,1989-04-23,187,90,Slovakia,GÃ³rnik Zabrze
...,...,...,...,...,...,...,...
Pedro LeÃ³n,Pedro LeÃ³n SÃ¡nchez Gil,32,1986-11-24,183,73,Spain,SD Eibar
M. Sykes,Mark Sykes,21,1997-08-04,182,78,Northern Ireland,Oxford United
Y. Fofana,Yahia Fofana,18,2000-08-21,194,89,France,Le Havre AC
A. Micai,Alessandro Micai,25,1993-07-24,186,77,Italy,US Salernitana 1919
David Bruno,David Dias Resende Bruno,27,1992-02-14,175,64,Portugal,Astra Giurgiu

In [5]:
# upsample: increase the sampling rate -> frac>1  (Note: replace parameter has to be True for frac parameter > 1)
df.sample(frac=2, replace=True, random_state=99)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
M. Hauptmeijer,Mike Hauptmeijer,22,1997-03-18,191,70,Netherlands,PEC Zwolle
A. Mosquera,AndrÃ©s Mosquera,29,1990-02-20,182,80,Colombia,Club LeÃ³n
V. Thill,Vincent Thill,19,2000-02-04,172,58,Luxembourg,US OrlÃ©ans Loiret Football
D. Bouanga,Denis Bouanga,24,1994-11-11,180,70,Gabon,AS Saint-Ãtienne
S. Al Selouli,Saad Al Selouli,21,1998-05-25,168,57,Saudi Arabia,Ettifaq FC
...,...,...,...,...,...,...,...
M. Connor,Matthew Connor,22,1997-04-08,192,82,Republic of Ireland,Waterford FC
J. Northcott,Jordan Northcott,17,2002-02-09,162,60,Scotland,St. Johnstone FC
A. Bodzek,Adam Bodzek,33,1985-09-07,184,81,Poland,Fortuna DÃ¼sseldorf
J. Adebayo-Smith,Jordan Adebayo-Smith,18,2001-01-11,181,77,United States,Lincoln City
F. Mac Allister,Francis Manuel Mac Allister,23,1995-10-30,176,71,Argentina,Argentinos Juniors