In [2]:
import pandas as pd

dataset = pd.read_excel("../../datasets/Boston.xlsx")

dataset.head(5)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,House_Price
0,0.0063,18,2.31,0,0.538,6.57,65.2,4.09,1,296,15.3,396.9,4.98,24.0
1,0.0273,0,7.07,0,0.469,6.42,78.9,4.97,2,242,17.8,396.9,9.14,21.6
2,0.0324,0,2.18,0,0.458,6.58,89.3,4.56,3,222,18.7,394.6,7.79,34.7
3,0.0690,0,4.05,0,0.410,6.95,82.5,3.95,4,254,16.1,390.5,5.33,33.4
4,0.0292,0,2.18,0,0.458,6.43,80.8,4.38,3,222,18.7,394.1,6.36,36.2

In [3]:
input_data = dataset.iloc[:,:-1]

In [4]:
input_data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.0063,18,2.31,0,0.538,6.57,65.2,4.09,1,296,15.3,396.9,4.98
1,0.0273,0,7.07,0,0.469,6.42,78.9,4.97,2,242,17.8,396.9,9.14
2,0.0324,0,2.18,0,0.458,6.58,89.3,4.56,3,222,18.7,394.6,7.79
3,0.0690,0,4.05,0,0.410,6.95,82.5,3.95,4,254,16.1,390.5,5.33
4,0.0292,0,2.18,0,0.458,6.43,80.8,4.38,3,222,18.7,394.1,6.36
5,0.0883,12,7.87,0,0.524,6.01,95.2,3.12,5,311,15.2,386.6,12.43
6,0.1445,0,10.01,0,0.547,5.89,96.7,2.87,6,305,17.4,380.2,15.76
7,0.2112,0,8.14,0,0.538,5.79,89.3,2.50,4,307,21.0,376.7,18.06
8,0.1700,0,5.64,1,0.499,6.38,73.4,3.12,3,280,17.0,390.9,13.27
9,0.2249,0,6.96,0,0.507,6.14,84.5,3.33,4,284,19.2,392.8,14.81

In [5]:
output_data = dataset['House_Price']

In [6]:
dataset.shape

(10, 14)

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train, x_test, y_train, y_test = train_test_split(input_data, output_data, test_size=0.25)

In [9]:
x_train

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
1,0.0273,0,7.07,0,0.469,6.42,78.9,4.97,2,242,17.8,396.9,9.14
8,0.1700,0,5.64,1,0.499,6.38,73.4,3.12,3,280,17.0,390.9,13.27
9,0.2249,0,6.96,0,0.507,6.14,84.5,3.33,4,284,19.2,392.8,14.81
4,0.0292,0,2.18,0,0.458,6.43,80.8,4.38,3,222,18.7,394.1,6.36
3,0.0690,0,4.05,0,0.410,6.95,82.5,3.95,4,254,16.1,390.5,5.33
5,0.0883,12,7.87,0,0.524,6.01,95.2,3.12,5,311,15.2,386.6,12.43
0,0.0063,18,2.31,0,0.538,6.57,65.2,4.09,1,296,15.3,396.9,4.98

In [10]:
x_train.shape

(7, 13)

In [11]:
y_train

1    21.6
8    23.1
9    20.6
4    36.2
3    33.4
5    22.9
0    24.0
Name: House_Price, dtype: float64

In [12]:
y_train.shape

(7,)

In [13]:
y_test

7    19.3
6    20.4
2    34.7
Name: House_Price, dtype: float64

In [14]:
x_test.shape, y_test.shape

((3, 13), (3,))