In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_rows", 200)

dataset =  pd.read_excel("../../datasets/groceries-groceries.xlsx")

dataset.head(5)

,Item1,Item2,Item3,Item4,Item5,Item6,Item7,Item8,Item9,Item10,Item11
0,Basmati,Toned Milk,Brown Eggs,Whole Wheat,Fuji,Cherry,Boneless,Dove,Colgate,Sunflower,White Sugar
1,Sona Masuri,Cow Milk,White Eggs,Multigrain,Gala,Roma,Curry Cut,Lux,Pepsodent,Mustard,Brown Sugar
2,Jasmine,Almond Milk,Organic Eggs,White Bread,Honeycrisp,Heirloom,Drumsticks,Pears,Sensodyne,Olive,Cane Sugar
3,Kolam,Buffalo Milk,Cage-Free,Rye Bread,Red Delicious,Plum,Thighs,Dettol,Close-Up,Groundnut,Castor Sugar
4,Biryani,Soy Milk,Duck Eggs,Sourdough,Granny Smith,Cherry,Whole,Santoor,Dabur Red,Coconut,Refined Sugar

In [2]:
market = []

for i in range(0, dataset.shape[0]):
    cus = []
    for j in dataset.columns:
        if type(dataset[j][i])==str:
            cus.append(dataset[j][i])
    market.append(cus)

In [3]:
market

[['Basmati',
  'Toned Milk',
  'Brown Eggs',
  'Whole Wheat',
  'Fuji',
  'Cherry',
  'Boneless',
  'Dove',
  'Colgate',
  'Sunflower',
  'White Sugar'],
 ['Sona Masuri',
  'Cow Milk',
  'White Eggs',
  'Multigrain',
  'Gala',
  'Roma',
  'Curry Cut',
  'Lux',
  'Pepsodent',
  'Mustard',
  'Brown Sugar'],
 ['Jasmine',
  'Almond Milk',
  'Organic Eggs',
  'White Bread',
  'Honeycrisp',
  'Heirloom',
  'Drumsticks',
  'Pears',
  'Sensodyne',
  'Olive',
  'Cane Sugar'],
 ['Kolam',
  'Buffalo Milk',
  'Cage-Free',
  'Rye Bread',
  'Red Delicious',
  'Plum',
  'Thighs',
  'Dettol',
  'Close-Up',
  'Groundnut',
  'Castor Sugar'],
 ['Biryani',
  'Soy Milk',
  'Duck Eggs',
  'Sourdough',
  'Granny Smith',
  'Cherry',
  'Whole',
  'Santoor',
  'Dabur Red',
  'Coconut',
  'Refined Sugar'],
 ['Ponni',
  'Oat Milk',
  'Quail Eggs',
  'Baguette',
  'Pink Lady',
  'Vine',
  'Minced',
  'Cinthol',
  'Himalaya',
  'Sesame',
  'Raw Sugar'],
 ['Long Grain',
  'Skim Milk',
  'Free-Range',
  'Brioche',
  'Golden',
  'Beefsteak',
  'Wings',
  'Medimix',
  'Oral-B',
  'Canola',
  'Palm Sugar'],
 ['Short Grain',
  'Full Cream',
  'Omega-3 Eggs',
  'Ciabatta',
  'Ambrosia',
  'Grape',
  'Breast',
  'Lifebuoy',
  'Patanjali',
  'Rice Bran',
  'Granulated'],
 ['Red Rice',
  'Goat Milk',
  'Farm Eggs',
  'Focaccia',
  'McIntosh',
  'San Marzano',
  'Legs',
  'Hamam',
  'Sensodyne',
  'Avocado',
  'Beet Sugar'],
 ['Brown Rice',
  'Raw Milk',
  'Jumbo Eggs',
  'Pita Bread',
  'Empire',
  'Campari',
  'Curry Cut',
  'Fiama',
  'Colgate',
  'Vegetable',
  'Icing Sugar'],
 ['Wild Rice',
  'Lactose-Free',
  'Duck Eggs',
  'Naan',
  'Braeburn',
  'Cherry',
  'Boneless',
  'Dettol',
  'Pepsodent',
  'Mustard',
  'White Sugar'],
 ['Arborio',
  'Rice Milk',
  'White Eggs',
  'Whole Wheat',
  'Honeycrisp',
  'Roma',
  'Drumsticks',
  'Pears',
  'Close-Up',
  'Olive',
  'Cane Sugar'],
 ['Sticky Rice',
  'Coconut Milk',
  'Brown Eggs',
  'Multigrain',
  'Gala',
  'Heirloom',
  'Thighs',
  'Lux',
  'Dabur Red',
  'Groundnut',
  'Castor Sugar'],
 ['Sushi Rice',
  'Cashew Milk',
  'Cage-Free',
  'Rye Bread',
  'Fuji',
  'Plum',
  'Whole',
  'Santoor',
  'Himalaya',
  'Coconut',
  'Refined Sugar'],
 ['Black Rice',
  'Hemp Milk',
  'Organic Eggs',
  'Sourdough',
  'Red Delicious',
  'Vine',
  'Minced',
  'Cinthol',
  'Oral-B',
  'Sesame',
  'Raw Sugar'],
 ['White Rice',
  'Skim Milk',
  'Free-Range',
  'Baguette',
  'Pink Lady',
  'Beefsteak',
  'Wings',
  'Medimix',
  'Patanjali',
  'Canola',
  'Palm Sugar'],
 ['Brown Rice',
  'Full Cream',
  'Omega-3 Eggs',
  'Brioche',
  'Golden',
  'Grape',
  'Breast',
  'Lifebuoy',
  'Sensodyne',
  'Rice Bran',
  'Granulated'],
 ['Red Rice',
  'Goat Milk',
  'Farm Eggs',
  'Ciabatta',
  'McIntosh',
  'San Marzano',
  'Legs',
  'Hamam',
  'Oral-B',
  'Avocado',
  'Beet Sugar'],
 ['Jasmine',
  'Raw Milk',
  'Jumbo Eggs',
  'Focaccia',
  'Empire',
  'Campari',
  'Curry Cut',
  'Fiama',
  'Colgate',
  'Vegetable',
  'Icing Sugar'],
 ['Sona Masuri',
  'Lactose-Free',
  'Duck Eggs',
  'Pita Bread',
  'Braeburn',
  'Cherry',
  'Boneless',
  'Dettol',
  'Pepsodent',
  'Mustard',
  'White Sugar']]

In [4]:
l = []
for i in market:
    for j in i:
        l.append(j)

In [5]:
l

['Basmati',
 'Toned Milk',
 'Brown Eggs',
 'Whole Wheat',
 'Fuji',
 'Cherry',
 'Boneless',
 'Dove',
 'Colgate',
 'Sunflower',
 'White Sugar',
 'Sona Masuri',
 'Cow Milk',
 'White Eggs',
 'Multigrain',
 'Gala',
 'Roma',
 'Curry Cut',
 'Lux',
 'Pepsodent',
 'Mustard',
 'Brown Sugar',
 'Jasmine',
 'Almond Milk',
 'Organic Eggs',
 'White Bread',
 'Honeycrisp',
 'Heirloom',
 'Drumsticks',
 'Pears',
 'Sensodyne',
 'Olive',
 'Cane Sugar',
 'Kolam',
 'Buffalo Milk',
 'Cage-Free',
 'Rye Bread',
 'Red Delicious',
 'Plum',
 'Thighs',
 'Dettol',
 'Close-Up',
 'Groundnut',
 'Castor Sugar',
 'Biryani',
 'Soy Milk',
 'Duck Eggs',
 'Sourdough',
 'Granny Smith',
 'Cherry',
 'Whole',
 'Santoor',
 'Dabur Red',
 'Coconut',
 'Refined Sugar',
 'Ponni',
 'Oat Milk',
 'Quail Eggs',
 'Baguette',
 'Pink Lady',
 'Vine',
 'Minced',
 'Cinthol',
 'Himalaya',
 'Sesame',
 'Raw Sugar',
 'Long Grain',
 'Skim Milk',
 'Free-Range',
 'Brioche',
 'Golden',
 'Beefsteak',
 'Wings',
 'Medimix',
 'Oral-B',
 'Canola',
 'Palm Sugar',
 'Short Grain',
 'Full Cream',
 'Omega-3 Eggs',
 'Ciabatta',
 'Ambrosia',
 'Grape',
 'Breast',
 'Lifebuoy',
 'Patanjali',
 'Rice Bran',
 'Granulated',
 'Red Rice',
 'Goat Milk',
 'Farm Eggs',
 'Focaccia',
 'McIntosh',
 'San Marzano',
 'Legs',
 'Hamam',
 'Sensodyne',
 'Avocado',
 'Beet Sugar',
 'Brown Rice',
 'Raw Milk',
 'Jumbo Eggs',
 'Pita Bread',
 'Empire',
 'Campari',
 'Curry Cut',
 'Fiama',
 'Colgate',
 'Vegetable',
 'Icing Sugar',
 'Wild Rice',
 'Lactose-Free',
 'Duck Eggs',
 'Naan',
 'Braeburn',
 'Cherry',
 'Boneless',
 'Dettol',
 'Pepsodent',
 'Mustard',
 'White Sugar',
 'Arborio',
 'Rice Milk',
 'White Eggs',
 'Whole Wheat',
 'Honeycrisp',
 'Roma',
 'Drumsticks',
 'Pears',
 'Close-Up',
 'Olive',
 'Cane Sugar',
 'Sticky Rice',
 'Coconut Milk',
 'Brown Eggs',
 'Multigrain',
 'Gala',
 'Heirloom',
 'Thighs',
 'Lux',
 'Dabur Red',
 'Groundnut',
 'Castor Sugar',
 'Sushi Rice',
 'Cashew Milk',
 'Cage-Free',
 'Rye Bread',
 'Fuji',
 'Plum',
 'Whole',
 'Santoor',
 'Himalaya',
 'Coconut',
 'Refined Sugar',
 'Black Rice',
 'Hemp Milk',
 'Organic Eggs',
 'Sourdough',
 'Red Delicious',
 'Vine',
 'Minced',
 'Cinthol',
 'Oral-B',
 'Sesame',
 'Raw Sugar',
 'White Rice',
 'Skim Milk',
 'Free-Range',
 'Baguette',
 'Pink Lady',
 'Beefsteak',
 'Wings',
 'Medimix',
 'Patanjali',
 'Canola',
 'Palm Sugar',
 'Brown Rice',
 'Full Cream',
 'Omega-3 Eggs',
 'Brioche',
 'Golden',
 'Grape',
 'Breast',
 'Lifebuoy',
 'Sensodyne',
 'Rice Bran',
 'Granulated',
 'Red Rice',
 'Goat Milk',
 'Farm Eggs',
 'Ciabatta',
 'McIntosh',
 'San Marzano',
 'Legs',
 'Hamam',
 'Oral-B',
 'Avocado',
 'Beet Sugar',
 'Jasmine',
 'Raw Milk',
 'Jumbo Eggs',
 'Focaccia',
 'Empire',
 'Campari',
 'Curry Cut',
 'Fiama',
 'Colgate',
 'Vegetable',
 'Icing Sugar',
 'Sona Masuri',
 'Lactose-Free',
 'Duck Eggs',
 'Pita Bread',
 'Braeburn',
 'Cherry',
 'Boneless',
 'Dettol',
 'Pepsodent',
 'Mustard',
 'White Sugar']

In [6]:
import collections

In [7]:
p=collections.Counter(l)

In [8]:
p.keys()

dict_keys(['Basmati', 'Toned Milk', 'Brown Eggs', 'Whole Wheat', 'Fuji', 'Cherry', 'Boneless', 'Dove', 'Colgate', 'Sunflower', 'White Sugar', 'Sona Masuri', 'Cow Milk', 'White Eggs', 'Multigrain', 'Gala', 'Roma', 'Curry Cut', 'Lux', 'Pepsodent', 'Mustard', 'Brown Sugar', 'Jasmine', 'Almond Milk', 'Organic Eggs', 'White Bread', 'Honeycrisp', 'Heirloom', 'Drumsticks', 'Pears', 'Sensodyne', 'Olive', 'Cane Sugar', 'Kolam', 'Buffalo Milk', 'Cage-Free', 'Rye Bread', 'Red Delicious', 'Plum', 'Thighs', 'Dettol', 'Close-Up', 'Groundnut', 'Castor Sugar', 'Biryani', 'Soy Milk', 'Duck Eggs', 'Sourdough', 'Granny Smith', 'Whole', 'Santoor', 'Dabur Red', 'Coconut', 'Refined Sugar', 'Ponni', 'Oat Milk', 'Quail Eggs', 'Baguette', 'Pink Lady', 'Vine', 'Minced', 'Cinthol', 'Himalaya', 'Sesame', 'Raw Sugar', 'Long Grain', 'Skim Milk', 'Free-Range', 'Brioche', 'Golden', 'Beefsteak', 'Wings', 'Medimix', 'Oral-B', 'Canola', 'Palm Sugar', 'Short Grain', 'Full Cream', 'Omega-3 Eggs', 'Ciabatta', 'Ambrosia', 'Grape', 'Breast', 'Lifebuoy', 'Patanjali', 'Rice Bran', 'Granulated', 'Red Rice', 'Goat Milk', 'Farm Eggs', 'Focaccia', 'McIntosh', 'San Marzano', 'Legs', 'Hamam', 'Avocado', 'Beet Sugar', 'Brown Rice', 'Raw Milk', 'Jumbo Eggs', 'Pita Bread', 'Empire', 'Campari', 'Fiama', 'Vegetable', 'Icing Sugar', 'Wild Rice', 'Lactose-Free', 'Naan', 'Braeburn', 'Arborio', 'Rice Milk', 'Sticky Rice', 'Coconut Milk', 'Sushi Rice', 'Cashew Milk', 'Black Rice', 'Hemp Milk', 'White Rice'])

In [9]:
p.values()

dict_values([1, 1, 2, 2, 2, 4, 3, 1, 3, 1, 3, 2, 1, 2, 2, 2, 2, 3, 2, 3, 3, 1, 2, 1, 2, 1, 2, 2, 2, 2, 3, 2, 2, 1, 1, 2, 2, 2, 2, 2, 3, 2, 2, 2, 1, 1, 3, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [10]:
d = {"Item Name":p.keys(), "values":p.values()}

In [11]:
pd.DataFrame(d).sort_values(by=["values"], ascending=False)

         Item Name  values
5           Cherry       4
6         Boneless       3
20         Mustard       3
17       Curry Cut       3
19       Pepsodent       3
10     White Sugar       3
8          Colgate       3
40          Dettol       3
46       Duck Eggs       3
30       Sensodyne       3
73          Oral-B       3
2       Brown Eggs       2
16            Roma       2
3      Whole Wheat       2
18             Lux       2
22         Jasmine       2
15            Gala       2
29           Pears       2
28      Drumsticks       2
24    Organic Eggs       2
14      Multigrain       2
13      White Eggs       2
4             Fuji       2
53   Refined Sugar       2
52         Coconut       2
50         Santoor       2
51       Dabur Red       2
42       Groundnut       2
43    Castor Sugar       2
27        Heirloom       2
26      Honeycrisp       2
37   Red Delicious       2
38            Plum       2
36       Rye Bread       2
35       Cage-Free       2
39          Thighs       2
41        Close-Up       2
32      Cane Sugar       2
31           Olive       2
49           Whole       2
47       Sourdough       2
72         Medimix       2
70       Beefsteak       2
67      Free-Range       2
66       Skim Milk       2
68         Brioche       2
69          Golden       2
59            Vine       2
64       Raw Sugar       2
62        Himalaya       2
61         Cinthol       2
57        Baguette       2
60          Minced       2
58       Pink Lady       2
11     Sona Masuri       2
103          Fiama       2
104      Vegetable       2
105    Icing Sugar       2
107   Lactose-Free       2
109       Braeburn       2
92     San Marzano       2
93            Legs       2
94           Hamam       2
95         Avocado       2
96      Beet Sugar       2
97      Brown Rice       2
98        Raw Milk       2
99      Jumbo Eggs       2
100     Pita Bread       2
71           Wings       2
63          Sesame       2
85       Rice Bran       2
81           Grape       2
82          Breast       2
74          Canola       2
75      Palm Sugar       2
77      Full Cream       2
78    Omega-3 Eggs       2
79        Ciabatta       2
86      Granulated       2
84       Patanjali       2
83        Lifebuoy       2
91        McIntosh       2
90        Focaccia       2
89       Farm Eggs       2
88       Goat Milk       2
87        Red Rice       2
101         Empire       2
102        Campari       2
54           Ponni       1
48    Granny Smith       1
23     Almond Milk       1
25     White Bread       1
44         Biryani       1
45        Soy Milk       1
12        Cow Milk       1
9        Sunflower       1
0          Basmati       1
1       Toned Milk       1
7             Dove       1
21     Brown Sugar       1
34    Buffalo Milk       1
33           Kolam       1
80        Ambrosia       1
76     Short Grain       1
56      Quail Eggs       1
65      Long Grain       1
55        Oat Milk       1
106      Wild Rice       1
108           Naan       1
110        Arborio       1
111      Rice Milk       1
112    Sticky Rice       1
113   Coconut Milk       1
114     Sushi Rice       1
115    Cashew Milk       1
116     Black Rice       1
117      Hemp Milk       1
118     White Rice       1

In [12]:
from mlxtend.preprocessing.transactionencoder import TransactionEncoder

In [13]:
tr = TransactionEncoder()
tr.fit(market)

c:\Users\Tushar Nile\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\externals\_numpydoc\docscrape.py:383: UserWarning: potentially wrong underline length...
Parameters
------------ in
Encoder class for transaction data in Python lists
...
  if not self._is_at_section():
c:\Users\Tushar Nile\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\externals\_numpydoc\docscrape.py:203: UserWarning: potentially wrong underline length...
Attributes
------------ in
Encoder class for transaction data in Python lists
...
  while not self._is_at_section() and not self._doc.eof():
c:\Users\Tushar Nile\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\externals\_numpydoc\docscrape.py:203: UserWarning: potentially wrong underline length...
Examples
------------ in
Encoder class for transaction data in Python lists
...
  while not self._is_at_section() and not self._doc.eof():

TransactionEncoder()

In [14]:
df = pd.DataFrame(tr.transform(market), columns=tr.columns_)

In [15]:
from mlxtend.frequent_patterns import apriori

In [16]:
apriori(df, min_support=0.05, use_colnames=True).sort_values(by=["support"])

       support                                           itemsets
38996     0.05  frozenset({Organic Eggs, Vine, Sourdough, Minc...
1         0.05                              frozenset({Ambrosia})
2         0.05                               frozenset({Arborio})
37492     0.05  frozenset({Close-Up, Roma, Honeycrisp, Olive, ...
37493     0.05  frozenset({Close-Up, Roma, Honeycrisp, Olive, ...
...        ...                                                ...
432       0.15                     frozenset({Cherry, Duck Eggs})
447       0.15                   frozenset({Cherry, White Sugar})
871       0.15                    frozenset({Pepsodent, Mustard})
1595      0.15         frozenset({Boneless, Cherry, White Sugar})
24        0.20                                frozenset({Cherry})

[39006 rows x 2 columns]