Max Voting, Averaging & Weighted Average Voting (Regression Practical)

In [1]:
import pandas as pd

dataset =  pd.read_csv("../../datasets/placement.csv")

dataset.head(5)

   cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [2]:
x = dataset.iloc[:, :-1]
y = dataset["package"]

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42, test_size=0.2)

In [5]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR

In [6]:
lr = LinearRegression()
lr.fit(x_train, y_train)
lr.score(x_train, y_train)*100, lr.score(x_test, y_test)*100

(77.58339025733345, 77.30984312051673)

In [7]:
dt = DecisionTreeRegressor()
dt.fit(x_train, y_train)
dt.score(x_train, y_train)*100, dt.score(x_test, y_test)*100

(95.1559200955432, 52.19733481708333)

In [8]:
sv = SVR()
sv.fit(x_train, y_train)

sv.score(x_train, y_train) * 100, sv.score(x_test, y_test) * 100

(78.16909319813372, 75.94945442913415)

In [9]:
from sklearn.ensemble import VotingRegressor

In [10]:
li = [("lr1", LinearRegression()),("dt1", DecisionTreeRegressor()), ("sv1", SVR())]

In [11]:
vc = VotingRegressor(li, weights=[10, 20, 30])
vc.fit(x_train, y_train)

VotingRegressor(estimators=[('lr1', LinearRegression()),
                            ('dt1', DecisionTreeRegressor()), ('sv1', SVR())],
                weights=[10, 20, 30])

In [12]:
vc.score(x_train, y_train) * 100, vc.score(x_test, y_test) * 100

(87.61049121022512, 74.7472381871813)

In [13]:
df = {"lr": lr.predict(x_test), "dt": dt.predict(x_test), "svm": sv.predict(x_test), "vc": vc.predict(x_test)}

In [14]:
pd.DataFrame(df).head(5)

         lr      dt       svm        vc
0  2.780313  2.9200  2.745462  2.809450
1  3.136352  3.2525  3.111375  3.162580
2  3.199521  2.9200  3.186923  3.100048
3  2.389819  2.5400  2.407183  2.448561
4  3.526847  3.9900  3.603909  3.719762